### ISSUE TITLE
403 from Github page when trying to download binaries

### ISSUE THREAD

**Issue by ManRueda** [shinnn/mkcert-prebuilt#4]
If you try to install this package in some linux environments (i cloud not found the right problem), GitHub returns 403 error when trying to download the binary from releases.

I found that this is related to the "User-Agent" header value, if `request` is used with the default one, GitHub blocks it. But if the header has other value it works.

**Comment by ManRueda** [comment]
I can't reproduce it locally. Only if i call from a VM inside AWS. But inside the same VM if i made the same request with `curl` it works, so it's not a connectivity problem.

**Comment by shinnn** [comment]
Can I ask

* why you need `mkcert` in AWS? As my understanding It's not a tool for production but for development.
* Node.js and npm CLI version in the VM

**Comment by ManRueda** [comment]
I have my CI (test, build, etc) on AWS. Its nothing public or production. Just testing.

Node.js: v10.15.3
npm: v6.9.0

**Comment by shinnn** [comment]
Thanks for the info, but,

> I can't reproduce it locally. Only if i call from a VM inside AWS.

then, the problem should be fixed on AWS side.
